### PR TITLE
Make expectations computation lazy.

### PR DESCRIPTION
**Pull request by dikmax**
Idea behind optimization that errorMessage we use only when needed but computing expectations all the time. And operations on sets are very expensive. So I delay this operation until it really needed.

My test started working twice fast.

### CODE REVIEW

**Comment by polux** [comment]
Nice! I think you could make it a bit shorter by using a linked list (I think I already have one elsewhere in the code, but I'm on my phone so it's cumbersome to check). I can merge you PR now and do the change myself, or you can give it a shit, as you wish.

Either way, thanks!

**Comment by dikmax** [comment]
Actually I can't see how LinkedList could help here. So make it yourself.
Thanks!

**Comment by polux** [comment]
I meant that EmptyExpectation | SingleExpectation | CombinedExpectation is isomorphic to LinkedList<Expectation>, more or less. I'll give it a try later but it's anyway already much better than how it was before.

**Comment by polux** [comment]
Published in version 0.14.5.

**Comment by polux** [comment]
Nevermind about my remark: what you want is not a list but a tree (or a list with lazy concatenation), which is exactly what you have.

**Pull request merged**
